version: '3'

networks:
    local:

services:
    postgres:
        image: postgres:12
        container_name: postgres
        expose:
            - ${PGPORT}/tcp
        ports:
            - ${PGPORT}:5432
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
        networks:
            - local

    adminer:
        image: adminer:latest
        container_name: adminer
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        networks:
            - local